### ISSUE TITLE
Repo dead?

### ISSUE THREAD

**Issue by nickescobedo** [BlockScore/blockscore-php#16]
Is this repo dead? 

I see an open pull request for PHP 7.2 compatibility and has no commits for over 2 years.

**Comment by dgollahon** [comment]
I will try to respond to issues / PRs that address significant incompatibilities or bugs. This repository does not receive frequent updates as most of our development resources have shifted to our https://cognitohq.com/ apis.

I may not always get back to you right away, but feel free to ping me periodically as needed.

**Comment by nickescobedo** [comment]
Thank you @dgollahon 
Does cognito do the same thing as blockscore or is it different?

**Comment by dgollahon** [comment]
They are similar, but not precisely the same. For the most common case of verifying the identity of an individual, either can be used but Cognito will generally have better outcomes. Each has some features that the other does not have, but Cognito is our focus/future direction.
