### ISSUE TITLE
Release PHP 7.2 object typehint fix

### ISSUE THREAD

**Issue by emelnychenko** [BlockScore/blockscore-php#19]
`Fatal error: Cannot use 'Object' as class name as it is reserved in ./vendor/blockscore/blockscore-php/lib/Object.php on line 16`

Here the reason: https://wiki.php.net/rfc/object-typehint

Thanks

**Comment by emelnychenko** [comment]
Okay, It's fixed here https://github.com/BlockScore/blockscore-php/commit/b7de9588818e0e50485019711c4895bc66004ebd but not released.

**Comment by dgollahon** [comment]
@emelnychenko The new version should be released. Let me know if, for some reason, it doesn't work for you.
