### ISSUE TITLE
Question sets are not getting scored correctly

### ISSUE THREAD

**Issue by andrewjkerr** [BlockScore/blockscore-php#8]
The PHP lib currently does not send a proper request to the BlockScore API resulting in incorrectly scored questions.

http://docs.blockscore.com/v4.0/curl/#score-a-question-set

**Comment by tjchambers** [comment]
If this is fixed why is it still open?

**Comment by alainmeier** [comment]
https://github.com/BlockScore/blockscore-php/pull/9 not closed yet

**Comment by backus** [comment]
@tjchambers could you review #9 possibly and then merge it if it seems good to you? I think one of us reviewed it back in the day but I just don't know much about PHP compared to you

**Comment by tjchambers** [comment]
@alainmeier The fix for this may work, but this is one of those very poorly implemented query parm concatenation code. It should be rewritten. I will rewrite it.

**Comment by alainmeier** [comment]
Thank you @tjchambers

**Comment by tjchambers** [comment]
@alainmeier Do you want the version bumped to 4.0.2 when I implement this on another PR?

**Comment by alainmeier** [comment]
@tjchambers yes please, I would like to get this pushed to package managers when it's done
